[package]
name = "scanner-cmd"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "*"
clap = { version = "3.1", features = ["derive"] }
nom = "7.1"
