name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            rustflags: -C target-feature=+crt-static
          - os: macos-latest
            target: x86_64-apple-darwin
            rustflags: -C target-feature=+crt-static
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Target Installed
      run: rustup target list --installed
    - name: Build
      run: cargo build --release --verbose
      env:
        RUSTFLAGS: ${{matrix.rustflags}}
        CARGO_BUILD_TARGET: ${{matrix.target}}
    - name: Run tests
      run: cargo test --verbose
      env:
        RUSTFLAGS: ${{matrix.rustflags}}
        TARGET: ${{matrix.target}}
