name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    strategy:
      matrix:
        system: [darwin, windows, linux]
        arch: [i686, x86_64]
        include:
          - system: windows
            os: windows-latest
            vendor: pc
            abi: -msvc
            rustflags: -C target-feature=+crt-static
          - system: darwin
            os: macos-latest
            vendor: apple
            abi: ""
            rustflags: -C target-feature=+crt-static
          - system: linux
            os: ubuntu-latest
            vendor: unknown
            abi: -gnu
            rustflags: ""
        exclude:
          - system: darwin
            arch: i686
          - system: linux
            arch: i686

    runs-on: ${{ matrix.os }}
    
    env:
      CARGO_BUILD_TARGET: ${{matrix.arch}}-${{matrix.vendor}}-${{matrix.system}}${{matrix.abi}}
      RUSTFLAGS: ${{matrix.rustflags}}

    steps:
    - uses: actions/checkout@v2
    - name: Target Installed
      run: rustup target list --installed
    - name: Build
      run: cargo build --release --verbose
    - name: Target (unix)
      run: ls -l target
      if: ${{ matrix.system != 'windows' }}
    - name: Target (win)
      run: dir target
      if: ${{ matrix.system == 'windows' }}
    - name: Run tests
      run: cargo test --verbose
